apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  name: {{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "app.name" . }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage }}